package tartan.combination;

/**
 * Created by HomeM5 on 01/12/2014.
 */
public enum OPERATION {
    COMBINE_CONCATENATION,
    COMBINE_ODD_EVEN,
    COMBINE_SUBTRACT,
    COMBINE_COMPOSITE,
    COMBINE_ADD,
    COMBINE_AVERAGE,
    COMBINE_RANDOMISE,
    INVERT_COLOUR,
    DARKER_COLOUR,
    BRIGHTER_COLOUR
}
